config/routes.rb
Todo::Application.routes.draw do
  root :to => 'tasks#index'
  get '/tasks/new', :controller => :tasks, :action => :new, :as => "new_task"
  get '/tasks', :controller => :tasks, :action => :index, :as => "tasks"
  post '/tasks', :controller => :tasks, :action => :create
  get '/tasks/:id', :controller => :tasks, :action => :show, :as => "task"
  delete '/tasks/:id', :controller => :tasks, :action => :destroy

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
  end

  def create
    Task.create(params[:task])
    redirect_to tasks_path
  end

  def show
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to tasks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>

<ul id='tasks'>
  <% @tasks.each do |task| %>
    <li id='task_<%= task.id %>'><%= task.name %><%= link_to "Delete this Task", task, :method => 'delete'%></li>
  <% end %>
</ul>

<%= link_to "Create a new Task", new_task_path %>

app/views/tasks/new.html.erb
<%= form_tag(tasks_path, :method => "post", :id => 'new_task' ) do %>
  <%= label_tag(:task_name, 'Name') %>
  <%= text_field_tag('task[name]') # task[name] => params = { :task => {:name => … }}
  %>
  <%= submit_tag("Create Task") %>
<% end %>